# Generated by Django 4.2.7 on 2025-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack_app', '0003_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='action_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Discount percentage 0-100'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='delivery_score',
            field=models.FloatField(default=0, help_text='Delivery score out of 5'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='response_rate',
            field=models.FloatField(default=0, help_text='Response rate percentage'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='approved', max_length=20),
        ),
    ]
