# Generated by Django 4.2.7 on 2025-11-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack_app', '0004_alter_alert_options_alert_action_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
