# Generated by Django 4.2.7 on 2025-11-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack_app', '0005_userrole_rejected_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchased_at']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='gateway_response',
            field=models.TextField(blank=True, help_text='JSON response from payment gateway', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('cellfin', 'CellFin'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Payment Initiated'), ('pending', 'Pending'), ('success', 'Payment Success'), ('failed', 'Payment Failed'), ('canceled', 'Payment Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freshtrack_app.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
