# Generated by Django 4.2.7 on 2025-11-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshtrack_app', '0006_alter_purchase_options_purchase_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='Manual discount percentage (0-90)'),
        ),
    ]
